/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaProyectoFinal;

import Controlador.CtrlAlumno;
import Controlador.ListaAlum;

/**
 *
 * @author Paccha
 */
public class AgregarAlumnosMateria extends javax.swing.JFrame {

    ListaAlum L = new ListaAlum();
    public AgregarAlumnosMateria() {
        initComponents();

        setLocationRelativeTo(null);
        setSize(400, 680);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        txtGrado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtEstudiante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AgregarLista = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre Materia: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 50, 97, 16);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(36, 83, 0, 0);

        jLabel3.setText("Nombe grado: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 100, 82, 16);
        getContentPane().add(txtMateria);
        txtMateria.setBounds(180, 50, 120, 24);
        getContentPane().add(txtGrado);
        txtGrado.setBounds(180, 100, 120, 24);

        jLabel4.setText("Agregar Estudiante:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 160, 112, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 410, 375, 177);

        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 300, 60, 10);
        getContentPane().add(txtEstudiante);
        txtEstudiante.setBounds(190, 200, 140, 24);

        jLabel6.setText("Apellido Estudiante:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 230, 111, 16);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(190, 290, 140, 30);

        jLabel7.setText("Nombre Estudiante:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 200, 111, 16);
        getContentPane().add(txtApellido);
        txtApellido.setBounds(190, 230, 140, 24);

        jLabel8.setText("Correo:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 260, 42, 16);
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(190, 260, 140, 24);

        jLabel9.setText("Lista de estudiantes : ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 380, 200, 16);

        AgregarLista.setText("Agregar a la lista");
        AgregarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarListaActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarLista);
        AgregarLista.setBounds(140, 330, 180, 32);

        jButton2.setText("Eliminar estudiante");
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 600, 150, 32);

        jLabel10.setText("Ejem: TerceroA");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(320, 110, 90, 16);

        jLabel11.setText("Agregar materia:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 10, 120, 20);

        jButton3.setText("Agg notas ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 600, 140, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuDocente MD = new MenuDocente();
        MD.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AgregarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarListaActionPerformed
        // TODO add your handling code here:
        CtrlAlumno Al = new CtrlAlumno();
        Al.CrearAlumno(txtMateria.getText(), txtGrado.getText(), txtEstudiante.getText(), txtApellido.getText(), txtCorreo.getText(), txtTelefono.getText());
       
    }//GEN-LAST:event_AgregarListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnosMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnosMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnosMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnosMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarAlumnosMateria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarLista;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEstudiante;
    private javax.swing.JTextField txtGrado;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
