/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaProyectoFinal;

import Controlador.CtrlAlumno;
import Controlador.CtrlTxt;
import Controlador.ListaAlum;
import Controlador.ListaNombresTxt;
import Modelo.*; 
import VistaProyectoFinal.Tablas.TablaEstudiantes;
import VistaProyectoFinal.Tablas.TablaNombres;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Paccha
 */
public class AgregarAlumnosMateria extends javax.swing.JFrame {
    FondoPanel2 fondo = new FondoPanel2(); 
    ListaAlum L = new ListaAlum();
    TablaEstudiantes T = new TablaEstudiantes();
    CtrlTxt C = new CtrlTxt();
    ListaNombresTxt Lt = new ListaNombresTxt();
    TablaNombres Tn = new TablaNombres();
    private int Seleccion;
    
     

    public AgregarAlumnosMateria() {
        initComponents();
        Guardartxt.setEnabled(false);
        jbtCrearNuevaLista.setEnabled(false);
        jButton1.setEnabled(false);
      // this.setContentPane(fondo);
    }

    public void campos() {
        if (txtEstudiante.getText().isEmpty() || txtApellido.getText().isEmpty()) {
            labelinfor.setText("Faltan datos");
        } else {
            labelinfor.setText("");
        }
        if (txtCorreo.getText().isEmpty()) {
            labelcorreo.setText("CAMPO NECESARIO");
        } else {
            labelcorreo.setText("");
        }
        if (txtTelefono.getText().isEmpty()) {
            labeltelefono.setText("CAMPO NECESARIO");
        } else {
            labeltelefono.setText("");
        }
        if (txtCodigo.getText().isEmpty()) {
            labelcodigo.setText("CAMPO NECESARIO");
        } else {
            labelcodigo.setText("");
        }
        if (txtEstudiante.getText().isEmpty() || txtApellido.getText().isEmpty()
                || txtCorreo.getText().isEmpty() || txtTelefono.getText().isEmpty()
                || txtCodigo.getText().isEmpty()) {
            Guardartxt.setEnabled(false);
            jbtCrearNuevaLista.setEnabled(false);
            jButton1.setEnabled(false);
        } else {
            Guardartxt.setEnabled(true);
            jbtCrearNuevaLista.setEnabled(true);
            jButton1.setEnabled(true);
        }

    }

    public void confirmaringreso() {
        if (txtMateria.getText().isEmpty() || txtGrado.getText().isEmpty()) {
            labelnombregrado.setText("CAMPOS FALTANTES");
        } else {
            labelnombregrado.setText("");
        }
    }

    private void cargarTabla() {
        T.setList(L);
        jTableAlumnos.setModel(T);
        jTableAlumnos.updateUI();
    }

    private void cargarTablaN() {
        Tn.setList(Lt);
        jTableNombres.setModel(Tn);
        jTableNombres.updateUI();
    }

    private void LimpiarCampos() {
        txtEstudiante.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        txtTelefono.setText("");
        txtCodigo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMateria = new javax.swing.JTextField();
        txtGrado = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlumnos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtEstudiante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AgregarLista = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Cargartxt = new javax.swing.JButton();
        Guardartxt = new javax.swing.JButton();
        jbtCrearNuevaLista = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNombres = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        ListasCreadas = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        labelnombregrado = new javax.swing.JLabel();
        labelcorreo = new javax.swing.JLabel();
        labeltelefono = new javax.swing.JLabel();
        labelcodigo = new javax.swing.JLabel();
        labelinfor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nombre Materia: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 94, 16);

        jLabel3.setText("Nombre grado: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 90, 100, 16);

        txtMateria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMateriaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMateriaKeyTyped(evt);
            }
        });
        getContentPane().add(txtMateria);
        txtMateria.setBounds(120, 50, 200, 24);

        txtGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGradoActionPerformed(evt);
            }
        });
        txtGrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGradoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGradoKeyTyped(evt);
            }
        });
        getContentPane().add(txtGrado);
        txtGrado.setBounds(120, 90, 200, 24);

        jTableAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAlumnos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 450, 650, 177);

        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 290, 60, 10);

        txtEstudiante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEstudianteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstudianteKeyTyped(evt);
            }
        });
        getContentPane().add(txtEstudiante);
        txtEstudiante.setBounds(130, 190, 140, 24);

        jLabel6.setText("Apellido Estudiante:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 220, 109, 16);

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(130, 280, 140, 30);

        jLabel7.setText("Nombre Estudiante:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 190, 110, 16);

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellido);
        txtApellido.setBounds(130, 220, 140, 24);

        jLabel8.setText("Correo:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 250, 41, 16);

        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(130, 250, 140, 24);

        jLabel9.setText("Lista de estudiantes : ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 410, 200, 16);

        AgregarLista.setText("Agregar a la lista");
        AgregarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarListaActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarLista);
        AgregarLista.setBounds(10, 360, 180, 24);

        jLabel10.setText("Ejem: TerceroA");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(330, 90, 90, 30);

        jLabel11.setText("    Registro de Alumnos en su respetiva materia");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 10, 280, 30);

        Cargartxt.setText("Cargar");
        Cargartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargartxtActionPerformed(evt);
            }
        });
        getContentPane().add(Cargartxt);
        Cargartxt.setBounds(440, 340, 77, 24);

        Guardartxt.setText("Guadar ");
        Guardartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardartxtActionPerformed(evt);
            }
        });
        getContentPane().add(Guardartxt);
        Guardartxt.setBounds(50, 640, 90, 24);

        jbtCrearNuevaLista.setText("Nuevo Curso");
        jbtCrearNuevaLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCrearNuevaListaActionPerformed(evt);
            }
        });
        getContentPane().add(jbtCrearNuevaLista);
        jbtCrearNuevaLista.setBounds(50, 680, 120, 24);

        jButton1.setText("Agregar Notas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(540, 640, 120, 24);

        jLabel12.setText("Codigo");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 324, 60, 20);

        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(130, 320, 140, 30);

        jTableNombres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableNombres);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(440, 230, 230, 100);

        jLabel13.setText("Agregar Estudiante:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 160, 108, 16);

        ListasCreadas.setText("Mostrar Listas");
        ListasCreadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListasCreadasActionPerformed(evt);
            }
        });
        getContentPane().add(ListasCreadas);
        ListasCreadas.setBounds(440, 190, 140, 24);

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 360, 90, 24);

        labelnombregrado.setFont(new java.awt.Font("Dubai", 3, 12)); // NOI18N
        labelnombregrado.setForeground(new java.awt.Color(204, 0, 0));
        labelnombregrado.setText(" ");
        getContentPane().add(labelnombregrado);
        labelnombregrado.setBounds(120, 120, 200, 20);

        labelcorreo.setFont(new java.awt.Font("Dubai", 3, 12)); // NOI18N
        labelcorreo.setForeground(new java.awt.Color(255, 0, 51));
        labelcorreo.setText(" ");
        getContentPane().add(labelcorreo);
        labelcorreo.setBounds(280, 260, 120, 21);

        labeltelefono.setFont(new java.awt.Font("Dubai", 3, 12)); // NOI18N
        labeltelefono.setForeground(new java.awt.Color(255, 51, 51));
        labeltelefono.setText(" ");
        getContentPane().add(labeltelefono);
        labeltelefono.setBounds(280, 290, 120, 21);

        labelcodigo.setFont(new java.awt.Font("Dubai", 3, 12)); // NOI18N
        labelcodigo.setForeground(new java.awt.Color(255, 0, 0));
        labelcodigo.setText(" ");
        getContentPane().add(labelcodigo);
        labelcodigo.setBounds(280, 330, 120, 16);

        labelinfor.setFont(new java.awt.Font("Dubai", 3, 12)); // NOI18N
        labelinfor.setForeground(new java.awt.Color(204, 0, 51));
        labelinfor.setText(" ");
        getContentPane().add(labelinfor);
        labelinfor.setBounds(280, 190, 100, 20);

        setSize(new java.awt.Dimension(731, 809));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarListaActionPerformed
        // TODO add your handling code here:
        if (txtCodigo.getText().length() != 4) {
            JOptionPane.showMessageDialog(null, "El codigo debe contener solo 4 numeros");
        } else if (L.Buscar(L, txtCodigo.getText())) {
            JOptionPane.showMessageDialog(null, "Ya existe ese codigo");
        } else {
            CtrlAlumno Al = new CtrlAlumno();
            Al.CrearAlumno(txtEstudiante.getText(), txtApellido.getText(), txtCorreo.getText(), txtTelefono.getText(), txtCodigo.getText());
            L.Agregar(Al.getA());
            cargarTabla();
            LimpiarCampos();
            L.Ordenar(L, 0, L.tamaño() - 1);
        }
    }//GEN-LAST:event_AgregarListaActionPerformed

    private void GuardartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardartxtActionPerformed

        String Nombre = "Lista";
        Nombre = Nombre + txtMateria.getText() + txtGrado.getText();
        C.GuardarTxt(L, Nombre);
        if (!Lt.Buscar(L, Nombre)) {
            Lt.Agregar(Nombre);
            Lt.Mostrar();
            C.GuardarNombresTxt(Lt, "ListaNombres");
            cargarTablaN();
        }


    }//GEN-LAST:event_GuardartxtActionPerformed

    private void CargartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargartxtActionPerformed
        if (txtGrado.getText().length() == 0 && txtMateria.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Rellene los campos de Materia y Grado");
        } else {
            String Nombre = "Lista";
            Nombre = Nombre + txtMateria.getText() + txtGrado.getText();
            // System.out.println(Nombre);
            L = C.CargarTxt(Nombre);
            cargarTabla();
        }
    }//GEN-LAST:event_CargartxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        AgregarNotas A = new AgregarNotas();
        A.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtCrearNuevaListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCrearNuevaListaActionPerformed
        int op = Integer.parseInt(JOptionPane.showInputDialog("¿ Desea Conservar la lista de alumnos actual \n (Esto no afectara sus datos actuales(  ?\n"
                + "1. Si"
                + "\n2. No"));
        if (op == 1) {
            txtGrado.setText("");
            txtMateria.setText("");
            LimpiarCampos();
        } else {
            L = new ListaAlum();
            cargarTabla();
        }
    }//GEN-LAST:event_jbtCrearNuevaListaActionPerformed

    private void ListasCreadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListasCreadasActionPerformed
        if (C.CargarNombresTxt("ListaNombres") == null) {
            JOptionPane.showMessageDialog(null, "Aun no hay listas creadas");
        } else {
            Lt = C.CargarNombresTxt("ListaNombres");
            cargarTablaN();
        }

    }//GEN-LAST:event_ListasCreadasActionPerformed

    private void jTableAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlumnosMouseClicked
        Seleccion = jTableAlumnos.rowAtPoint(evt.getPoint());
        txtEstudiante.setText(String.valueOf(jTableAlumnos.getValueAt(Seleccion, 0)));
        txtApellido.setText(String.valueOf(jTableAlumnos.getValueAt(Seleccion, 1)));
        txtTelefono.setText(String.valueOf(jTableAlumnos.getValueAt(Seleccion, 2)));
        txtCorreo.setText(String.valueOf(jTableAlumnos.getValueAt(Seleccion, 3)));
    }//GEN-LAST:event_jTableAlumnosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txtCodigo.getText().length() > 0) {
            JOptionPane.showMessageDialog(null, " No se puede modificar el Codigo");
        } else {
            L.ObtenerDato(Seleccion).setNombre(txtEstudiante.getText());
            L.ObtenerDato(Seleccion).setApellido(txtApellido.getText());
            L.ObtenerDato(Seleccion).setCorreo(txtCorreo.getText());
            L.ObtenerDato(Seleccion).setCelular(txtTelefono.getText());

            cargarTabla();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtMateriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMateriaKeyTyped
        // TODO add your handling code here:

        if (txtMateria.getText().length() >= 45) {
            evt.consume();
        }
    }//GEN-LAST:event_txtMateriaKeyTyped

    private void txtGradoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGradoKeyTyped
        // TODO add your handling code here:

        if (txtGrado.getText().length() >= 30) {
            evt.consume();
        }
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            evt.consume();
            labelnombregrado.setText("Solo letras");
        } else {
            labelnombregrado.setText("");
        }
        if (evt.getKeyChar() >= 32 && evt.getKeyChar() <= 32) {
            evt.consume();
            labelnombregrado.setText("Sin espacios");
        } else {
            labelnombregrado.setText("");
        }

    }//GEN-LAST:event_txtGradoKeyTyped

    private void txtMateriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMateriaKeyReleased
        // TODO add your handling code here:
        confirmaringreso();
        campos();
    }//GEN-LAST:event_txtMateriaKeyReleased

    private void txtGradoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGradoKeyReleased
        // TODO add your handling code here:
        confirmaringreso();
        campos();
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            evt.consume();
            labelnombregrado.setText("Solo letras");
        } else {
            labelnombregrado.setText("");
        }
    }//GEN-LAST:event_txtGradoKeyReleased

    private void txtGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGradoActionPerformed

    private void txtEstudianteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstudianteKeyReleased
        // TODO add your handling code here:
        confirmaringreso();
        campos();
    }//GEN-LAST:event_txtEstudianteKeyReleased

    private void txtApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyReleased
        // TODO add your handling code here:
        confirmaringreso();
        campos();
    }//GEN-LAST:event_txtApellidoKeyReleased

    private void txtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyReleased
        // TODO add your handling code here:
        confirmaringreso();
        campos();
        if (!txtCorreo.getText().contains("@") || !txtCorreo.getText().contains(".")) {
            labelcorreo.setText("CORREO INVALIDO");
        } else {
            labelcorreo.setText("");
        }
    }//GEN-LAST:event_txtCorreoKeyReleased

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        // TODO add your handling code here:
        confirmaringreso();
        campos();
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        // TODO add your handling code here:
        confirmaringreso();
        campos();
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void txtEstudianteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstudianteKeyTyped
        // TODO add your handling code here:
        if (txtEstudiante.getText().length() >= 45) {
            evt.consume();
        }
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
            labelinfor.setText("Solo letras");
        }
    }//GEN-LAST:event_txtEstudianteKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:

        if (txtApellido.getText().length() >= 45) {
            evt.consume();
        }
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
            labelinfor.setText("Solo letras");
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        // TODO add your handling code here:
        if (txtCodigo.getText().length() >= 4) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        if (txtTelefono.getText().length() >= 11) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            evt.consume();
            labeltelefono.setText("Solo numeros");
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtCorreoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnosMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnosMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnosMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnosMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarAlumnosMateria().setVisible(true);
            }
        });
    }
       class FondoPanel2 extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/imagenes/fondo.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
           
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarLista;
    private javax.swing.JButton Cargartxt;
    private javax.swing.JButton Guardartxt;
    private javax.swing.JButton ListasCreadas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAlumnos;
    private javax.swing.JTable jTableNombres;
    private javax.swing.JButton jbtCrearNuevaLista;
    private javax.swing.JLabel labelcodigo;
    private javax.swing.JLabel labelcorreo;
    private javax.swing.JLabel labelinfor;
    private javax.swing.JLabel labelnombregrado;
    private javax.swing.JLabel labeltelefono;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEstudiante;
    private javax.swing.JTextField txtGrado;
    private javax.swing.JTextField txtMateria;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}

