/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaProyectoFinal;

/**
 *
 * @author Paccha
 */
public class AgregarMateria extends javax.swing.JFrame {

    /**
     * Creates new form AgregarMateria
     */
    public AgregarMateria() {
        initComponents();

        setLocationRelativeTo(null);
        setSize(400, 680);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nombe Materia: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(36, 48, 92, 16);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(36, 83, 0, 0);

        jLabel3.setText("Nombe grado: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(36, 97, 82, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(125, 45, 120, 24);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(125, 94, 120, 24);

        jLabel4.setText("Agregar Estudiante:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 160, 112, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(15, 405, 375, 177);

        jLabel5.setText("Telefono:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 310, 50, 10);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(151, 195, 140, 24);

        jLabel6.setText("Apellido Estudiante:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 230, 111, 16);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(150, 310, 140, 20);

        jLabel7.setText("Nombre Estudiante:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 200, 111, 16);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(150, 230, 140, 24);

        jLabel8.setText("Correo:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(90, 270, 42, 16);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(150, 270, 140, 24);

        jLabel9.setText("Lista de estudiantes agregada: ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 380, 200, 16);

        jButton1.setText("Agregar a lista");
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 350, 120, 32);

        jButton2.setText("Eliminar estudiante");
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 600, 130, 32);

        jLabel10.setText("Ejem: TerceroA");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(260, 100, 90, 16);

        jLabel11.setText("Agregar materia:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 10, 120, 20);

        jButton3.setText("Agg notas ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(210, 600, 140, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuDocente MD = new MenuDocente();
        MD.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarMateria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarMateria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
